# Generated by Django 3.0.3 on 2020-03-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200302_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookclub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('Amenities', models.CharField(choices=[('Swimming Pool', 'Swimming Pool'), ('Basket Ball', 'Basket Ball'), ('FootBall', 'FootBall'), ('Tennis(court)', 'Tennis(court)'), ('Party Plot', 'Party Plot'), ('Banquet', 'Banquet'), ('Gym', 'Gym'), ('spa', 'spa'), ('Theatre', 'Theatre'), ('Gaming Zone', 'Gaming Zone')], max_length=15)),
                ('Date', models.DateField()),
            ],
        ),
    ]
